version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: moderation-bot-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moderation_bot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: moderation-bot
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ENVIRONMENT: ${ENVIRONMENT:-production}
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/moderation_bot
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  postgres_data:
